<?php

namespace Database\Seeders;

use App\Models\Wine;
use Illuminate\Database\Seeder;

class WineSeeder extends Seeder
{
    public function run(): void
    {
        $wines = [
            [
                'id'              => 'b1c2d3e4-0001-0001-0001-100000000001',
                'winery_id'       => 'a1b2c3d4-0001-0001-0001-000000000001',
                'name'            => 'Catena Adrianna Vineyard Malbec',
                'vintage'         => 2020,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Malbec de alta gama proveniente del viñedo Adrianna, a 1500m de altitud en Tupungato.',
                'description_en'  => 'Top-tier Malbec from the Adrianna Vineyard, 1500m altitude in Tupungato.',
                'alcohol_content' => 14.5,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 120.00,
                'price_max'       => 150.00,
                'image_url'       => null,
                'rating_average'  => 4.8,
                'rating_count'    => 120,
                'is_featured'     => true,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0002-0002-0002-100000000002',
                'winery_id'       => 'a1b2c3d4-0001-0001-0001-000000000001',
                'name'            => 'Catena Zapata Malbec',
                'vintage'         => 2021,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'El emblemático Malbec de Catena, expresión clásica del Malbec mendocino.',
                'description_en'  => 'The iconic Catena Malbec, a classic expression of Mendoza Malbec.',
                'alcohol_content' => 14.0,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 35.00,
                'price_max'       => 45.00,
                'image_url'       => null,
                'rating_average'  => 4.4,
                'rating_count'    => 95,
                'is_featured'     => true,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0003-0003-0003-100000000003',
                'winery_id'       => 'a1b2c3d4-0002-0002-0002-000000000002',
                'name'            => 'Luigi Bosca Malbec Reserva',
                'vintage'         => 2020,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Malbec reserva con crianza en roble francés, complejo y elegante.',
                'description_en'  => 'Reserve Malbec with French oak aging, complex and elegant.',
                'alcohol_content' => 14.0,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 25.00,
                'price_max'       => 35.00,
                'image_url'       => null,
                'rating_average'  => 4.2,
                'rating_count'    => 78,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0004-0004-0004-100000000004',
                'winery_id'       => 'a1b2c3d4-0003-0003-0003-000000000003',
                'name'            => 'Zuccardi Valle Malbec',
                'vintage'         => 2021,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Malbec del Valle de Uco, terroir de altura con mineralidad única.',
                'description_en'  => 'Valle de Uco Malbec, high altitude terroir with unique minerality.',
                'alcohol_content' => 14.5,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 18.00,
                'price_max'       => 25.00,
                'image_url'       => null,
                'rating_average'  => 4.3,
                'rating_count'    => 65,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0005-0005-0005-100000000005',
                'winery_id'       => 'a1b2c3d4-0004-0004-0004-000000000004',
                'name'            => 'Achaval Ferrer Quimera',
                'vintage'         => 2019,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec', 'Cabernet Sauvignon', 'Cabernet Franc', 'Merlot'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Blend de viñedos viejos, referente de la alta gama mendocina.',
                'description_en'  => 'Old vine blend, benchmark of Mendoza top tier.',
                'alcohol_content' => 14.0,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 45.00,
                'price_max'       => 60.00,
                'image_url'       => null,
                'rating_average'  => 4.6,
                'rating_count'    => 85,
                'is_featured'     => true,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0006-0006-0006-100000000006',
                'winery_id'       => 'a1b2c3d4-0001-0001-0001-000000000001',
                'name'            => 'Catena Chardonnay',
                'vintage'         => 2022,
                'wine_type'       => 'WHITE',
                'style'           => 'Medium-bodied',
                'grapes'          => ['Chardonnay'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Chardonnay con notas de frutas tropicales y toque de roble.',
                'description_en'  => 'Chardonnay with tropical fruit notes and subtle oak.',
                'alcohol_content' => 13.5,
                'serving_temp_min' => 8,
                'serving_temp_max' => 12,
                'price_min'       => 20.00,
                'price_max'       => 28.00,
                'image_url'       => null,
                'rating_average'  => 4.1,
                'rating_count'    => 55,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0007-0007-0007-100000000007',
                'winery_id'       => 'a1b2c3d4-0006-0006-0006-000000000006',
                'name'            => 'Don Melchor Cabernet Sauvignon',
                'vintage'         => 2019,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Cabernet Sauvignon'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'El vino ícono de Concha y Toro, expresión máxima del Cabernet de Puente Alto.',
                'description_en'  => 'Concha y Toro iconic wine, the ultimate expression of Puente Alto Cabernet.',
                'alcohol_content' => 14.5,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 80.00,
                'price_max'       => 100.00,
                'image_url'       => null,
                'rating_average'  => 4.7,
                'rating_count'    => 110,
                'is_featured'     => true,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0008-0008-0008-100000000008',
                'winery_id'       => 'a1b2c3d4-0007-0007-0007-000000000007',
                'name'            => 'Clos Apalta',
                'vintage'         => 2018,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Carménère', 'Cabernet Sauvignon', 'Merlot', 'Petit Verdot'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Clos Apalta, emblemático blend de Colchagua con Carménère como base.',
                'description_en'  => 'Clos Apalta, emblematic Colchagua blend with Carménère as base.',
                'alcohol_content' => 14.5,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 90.00,
                'price_max'       => 120.00,
                'image_url'       => null,
                'rating_average'  => 4.9,
                'rating_count'    => 95,
                'is_featured'     => true,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0009-0009-0009-100000000009',
                'winery_id'       => 'a1b2c3d4-0005-0005-0005-000000000005',
                'name'            => 'Clos de los Siete',
                'vintage'         => 2020,
                'wine_type'       => 'RED',
                'style'           => 'Full-bodied',
                'grapes'          => ['Malbec', 'Merlot', 'Syrah', 'Cabernet Sauvignon'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Blend del Valle de Uco, proyecto del enólogo Michel Rolland.',
                'description_en'  => 'Valle de Uco blend, project by winemaker Michel Rolland.',
                'alcohol_content' => 14.0,
                'serving_temp_min' => 16,
                'serving_temp_max' => 18,
                'price_min'       => 22.00,
                'price_max'       => 30.00,
                'image_url'       => null,
                'rating_average'  => 4.3,
                'rating_count'    => 72,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0010-0010-0010-100000000010',
                'winery_id'       => 'a1b2c3d4-0003-0003-0003-000000000003',
                'name'            => 'Zuccardi Emma Bonarda',
                'vintage'         => 2021,
                'wine_type'       => 'RED',
                'style'           => 'Medium-bodied',
                'grapes'          => ['Bonarda'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Bonarda refrescante y frutal, uva típica argentina.',
                'description_en'  => 'Refreshing and fruity Bonarda, typical Argentine variety.',
                'alcohol_content' => 13.5,
                'serving_temp_min' => 14,
                'serving_temp_max' => 16,
                'price_min'       => 12.00,
                'price_max'       => 18.00,
                'image_url'       => null,
                'rating_average'  => 4.0,
                'rating_count'    => 45,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0011-0011-0011-100000000011',
                'winery_id'       => 'a1b2c3d4-0002-0002-0002-000000000002',
                'name'            => 'Luigi Bosca Sauvignon Blanc',
                'vintage'         => 2022,
                'wine_type'       => 'WHITE',
                'style'           => 'Light-bodied',
                'grapes'          => ['Sauvignon Blanc'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Sauvignon Blanc fresco y cítrico de los viñedos de Luján.',
                'description_en'  => 'Fresh and citrusy Sauvignon Blanc from Luján vineyards.',
                'alcohol_content' => 12.5,
                'serving_temp_min' => 8,
                'serving_temp_max' => 10,
                'price_min'       => 15.00,
                'price_max'       => 22.00,
                'image_url'       => null,
                'rating_average'  => 3.9,
                'rating_count'    => 38,
                'is_featured'     => false,
                'is_active'       => true,
            ],
            [
                'id'              => 'b1c2d3e4-0012-0012-0012-100000000012',
                'winery_id'       => 'a1b2c3d4-0001-0001-0001-000000000001',
                'name'            => 'Catena Rosé',
                'vintage'         => 2022,
                'wine_type'       => 'ROSE',
                'style'           => 'Dry',
                'grapes'          => ['Malbec'],
                'allergens'       => ['sulfites'],
                'description_es'  => 'Rosado seco y elegante elaborado con Malbec de altura.',
                'description_en'  => 'Dry and elegant rosé made from high-altitude Malbec.',
                'alcohol_content' => 13.0,
                'serving_temp_min' => 8,
                'serving_temp_max' => 10,
                'price_min'       => 18.00,
                'price_max'       => 25.00,
                'image_url'       => null,
                'rating_average'  => 4.0,
                'rating_count'    => 42,
                'is_featured'     => false,
                'is_active'       => true,
            ],
        ];

        foreach ($wines as $wine) {
            Wine::firstOrCreate(['id' => $wine['id']], $wine);
        }
    }
}
